services:
    - docker
before-install:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
    - docker build -t $DOCKER_USERNAME/ionic-angular .
    - docker run -t -d $DOCKER_USERNAME/ionic-angular
    - docker push $DOCKER_USERNAME/ionic-angular:v5.2.4-7.2.4
