services:
    - docker
before-install:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
    - docker build -t v5.2.4-7.2.4 .
    - docker run -t -d v5.2.4-7.2.4
    - docker push dark4image/ionic-angular:v5.2.4-7.2.4
